export const GET_CATEGORIES="GET_CATEGORIES";
export const GET_SUBCATEGORIES="GET_SUBCATEGORIES";
export const GET_ALL_PRODUCTS='GET_ALL_PRODUCTS';
export const SCREEN_CHANGE='SCREEN_CHANGE';
export const POST_FINAL_CART='POST_FINAL_CART';
export const GET_FINAL_CART=' GET_FINAL_CART';